/**
 * Seed ~500 common household inventory items for the demo household.
 * Run: npx tsx prisma/seed-inventory.ts
 *
 * Safe to re-run: uses upsert by (householdId, name).
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ITEMS: { category: string; name: string; unit: string }[] = [
  // ─── Cleaning Supplies ─────────────────────────────────────────────────────
  { category: "Cleaning Supplies", name: "All-Purpose Cleaner", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Dish Soap", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Dishwasher Detergent Pods", unit: "pack" },
  { category: "Cleaning Supplies", name: "Dishwasher Rinse Aid", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Laundry Detergent (Liquid)", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Laundry Detergent (Pods)", unit: "pack" },
  { category: "Cleaning Supplies", name: "Fabric Softener", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Dryer Sheets", unit: "box" },
  { category: "Cleaning Supplies", name: "Bleach", unit: "bottle" },
  { category: "Cleaning Supplies", name: "OxiClean", unit: "tub" },
  { category: "Cleaning Supplies", name: "Glass Cleaner (Windex)", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Bathroom Scrubbing Cleanser", unit: "can" },
  { category: "Cleaning Supplies", name: "Toilet Bowl Cleaner", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Toilet Bowl Tablets", unit: "pack" },
  { category: "Cleaning Supplies", name: "Mold & Mildew Spray", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Floor Cleaner (Hardwood)", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Floor Cleaner (Tile)", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Mop Refill Pads", unit: "pack" },
  { category: "Cleaning Supplies", name: "Scrub Sponges", unit: "pack" },
  { category: "Cleaning Supplies", name: "Microfiber Cloths", unit: "pack" },
  { category: "Cleaning Supplies", name: "Magic Eraser Pads", unit: "pack" },
  { category: "Cleaning Supplies", name: "Rubber Gloves", unit: "pair" },
  { category: "Cleaning Supplies", name: "Steel Wool Pads", unit: "pack" },
  { category: "Cleaning Supplies", name: "Drain Unclogger (Liquid)", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Garbage Disposal Cleaner", unit: "pack" },
  { category: "Cleaning Supplies", name: "Stainless Steel Polish", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Wood Polish / Furniture Spray", unit: "can" },
  { category: "Cleaning Supplies", name: "Carpet Stain Remover", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Air Freshener Spray", unit: "can" },
  { category: "Cleaning Supplies", name: "Plug-In Air Freshener Refills", unit: "pack" },
  { category: "Cleaning Supplies", name: "Baking Soda (bulk cleaning)", unit: "box" },
  { category: "Cleaning Supplies", name: "White Vinegar (cleaning)", unit: "bottle" },
  { category: "Cleaning Supplies", name: "Disinfecting Wipes", unit: "canister" },
  { category: "Cleaning Supplies", name: "Vacuum Bags / Filters", unit: "pack" },
  { category: "Cleaning Supplies", name: "Trash Bags (tall kitchen)", unit: "box" },
  { category: "Cleaning Supplies", name: "Trash Bags (small bathroom)", unit: "box" },
  { category: "Cleaning Supplies", name: "Recycling Bags", unit: "box" },
  { category: "Cleaning Supplies", name: "Lint Roller Refills", unit: "pack" },

  // ─── Paper & Disposables ───────────────────────────────────────────────────
  { category: "Paper & Disposables", name: "Paper Towels", unit: "rolls" },
  { category: "Paper & Disposables", name: "Toilet Paper", unit: "rolls" },
  { category: "Paper & Disposables", name: "Facial Tissues (Kleenex)", unit: "box" },
  { category: "Paper & Disposables", name: "Paper Napkins", unit: "pack" },
  { category: "Paper & Disposables", name: "Paper Plates", unit: "pack" },
  { category: "Paper & Disposables", name: "Paper Bowls", unit: "pack" },
  { category: "Paper & Disposables", name: "Plastic Cups (disposable)", unit: "pack" },
  { category: "Paper & Disposables", name: "Plastic Cutlery Set", unit: "pack" },
  { category: "Paper & Disposables", name: "Aluminum Foil", unit: "roll" },
  { category: "Paper & Disposables", name: "Plastic Wrap (Saran Wrap)", unit: "roll" },
  { category: "Paper & Disposables", name: "Parchment Paper", unit: "roll" },
  { category: "Paper & Disposables", name: "Wax Paper", unit: "roll" },
  { category: "Paper & Disposables", name: "Plastic Food Storage Bags (gallon)", unit: "box" },
  { category: "Paper & Disposables", name: "Plastic Food Storage Bags (quart)", unit: "box" },
  { category: "Paper & Disposables", name: "Plastic Food Storage Bags (sandwich)", unit: "box" },
  { category: "Paper & Disposables", name: "Coffee Filters", unit: "pack" },
  { category: "Paper & Disposables", name: "Cupcake / Muffin Liners", unit: "pack" },

  // ─── Kitchen & Cooking ─────────────────────────────────────────────────────
  { category: "Kitchen & Cooking", name: "Cooking Oil (Olive)", unit: "bottle" },
  { category: "Kitchen & Cooking", name: "Cooking Oil (Vegetable)", unit: "bottle" },
  { category: "Kitchen & Cooking", name: "Cooking Spray (PAM)", unit: "can" },
  { category: "Kitchen & Cooking", name: "Butter (unsalted)", unit: "lb" },
  { category: "Kitchen & Cooking", name: "Butter (salted)", unit: "lb" },
  { category: "Kitchen & Cooking", name: "Salt (table)", unit: "container" },
  { category: "Kitchen & Cooking", name: "Black Pepper (ground)", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Garlic Powder", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Onion Powder", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Paprika", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Cumin", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Oregano", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Basil (dried)", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Thyme (dried)", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Cayenne Pepper", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Cinnamon (ground)", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Chili Powder", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Italian Seasoning", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Red Pepper Flakes", unit: "jar" },
  { category: "Kitchen & Cooking", name: "Bay Leaves", unit: "jar" },
  { category: "Kitchen & Cooking", name: "White Sugar", unit: "bag" },
  { category: "Kitchen & Cooking", name: "Brown Sugar", unit: "bag" },
  { category: "Kitchen & Cooking", name: "Powdered Sugar", unit: "bag" },
  { category: "Kitchen & Cooking", name: "All-Purpose Flour", unit: "bag" },
  { category: "Kitchen & Cooking", name: "Bread Flour", unit: "bag" },
  { category: "Kitchen & Cooking", name: "Baking Powder", unit: "can" },
  { category: "Kitchen & Cooking", name: "Baking Soda", unit: "box" },
  { category: "Kitchen & Cooking", name: "Yeast (active dry)", unit: "pack" },
  { category: "Kitchen & Cooking", name: "Vanilla Extract", unit: "bottle" },
  { category: "Kitchen & Cooking", name: "Cocoa Powder", unit: "can" },
  { category: "Kitchen & Cooking", name: "Cornstarch", unit: "box" },
  { category: "Kitchen & Cooking", name: "White Rice", unit: "bag" },
  { category: "Kitchen & Cooking", name: "Brown Rice", unit: "bag" },
  { category: "Kitchen & Cooking", name: "Pasta (spaghetti)", unit: "box" },
  { category: "Kitchen & Cooking", name: "Pasta (penne)", unit: "box" },
  { category: "Kitchen & Cooking", name: "Pasta (rotini)", unit: "box" },
  { category: "Kitchen & Cooking", name: "Oatmeal (rolled oats)", unit: "container" },
  { category: "Kitchen & Cooking", name: "Bread Crumbs", unit: "can" },
  { category: "Kitchen & Cooking", name: "Panko Bread Crumbs", unit: "bag" },

  // ─── Pantry Staples ────────────────────────────────────────────────────────
  { category: "Pantry Staples", name: "Chicken Broth / Stock", unit: "carton" },
  { category: "Pantry Staples", name: "Vegetable Broth", unit: "carton" },
  { category: "Pantry Staples", name: "Diced Tomatoes (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Tomato Sauce (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Tomato Paste", unit: "can" },
  { category: "Pantry Staples", name: "Crushed Tomatoes", unit: "can" },
  { category: "Pantry Staples", name: "Black Beans (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Kidney Beans (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Chickpeas / Garbanzo (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Coconut Milk (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Tuna (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Salmon (canned)", unit: "can" },
  { category: "Pantry Staples", name: "Peanut Butter", unit: "jar" },
  { category: "Pantry Staples", name: "Almond Butter", unit: "jar" },
  { category: "Pantry Staples", name: "Jelly / Jam (strawberry)", unit: "jar" },
  { category: "Pantry Staples", name: "Honey", unit: "jar" },
  { category: "Pantry Staples", name: "Maple Syrup", unit: "bottle" },
  { category: "Pantry Staples", name: "Apple Cider Vinegar", unit: "bottle" },
  { category: "Pantry Staples", name: "Balsamic Vinegar", unit: "bottle" },
  { category: "Pantry Staples", name: "Soy Sauce", unit: "bottle" },
  { category: "Pantry Staples", name: "Worcestershire Sauce", unit: "bottle" },
  { category: "Pantry Staples", name: "Hot Sauce (Tabasco)", unit: "bottle" },
  { category: "Pantry Staples", name: "Ketchup", unit: "bottle" },
  { category: "Pantry Staples", name: "Yellow Mustard", unit: "bottle" },
  { category: "Pantry Staples", name: "Dijon Mustard", unit: "jar" },
  { category: "Pantry Staples", name: "Mayonnaise", unit: "jar" },
  { category: "Pantry Staples", name: "Ranch Dressing", unit: "bottle" },
  { category: "Pantry Staples", name: "Olive Oil Spray", unit: "can" },
  { category: "Pantry Staples", name: "Sriracha", unit: "bottle" },
  { category: "Pantry Staples", name: "Salsa", unit: "jar" },
  { category: "Pantry Staples", name: "Salad Dressing (Italian)", unit: "bottle" },
  { category: "Pantry Staples", name: "Salad Dressing (Caesar)", unit: "bottle" },
  { category: "Pantry Staples", name: "Pasta Sauce (marinara)", unit: "jar" },
  { category: "Pantry Staples", name: "Soy Sauce (low sodium)", unit: "bottle" },

  // ─── Snacks & Breakfast ────────────────────────────────────────────────────
  { category: "Snacks & Breakfast", name: "Granola Bars", unit: "box" },
  { category: "Snacks & Breakfast", name: "Protein Bars", unit: "box" },
  { category: "Snacks & Breakfast", name: "Trail Mix", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Mixed Nuts", unit: "can" },
  { category: "Snacks & Breakfast", name: "Almonds", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Cashews", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Walnuts", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Peanuts", unit: "can" },
  { category: "Snacks & Breakfast", name: "Crackers (Wheat Thins)", unit: "box" },
  { category: "Snacks & Breakfast", name: "Crackers (Ritz)", unit: "box" },
  { category: "Snacks & Breakfast", name: "Pretzels", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Potato Chips", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Popcorn (microwave)", unit: "pack" },
  { category: "Snacks & Breakfast", name: "Tortilla Chips", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Rice Cakes", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Dried Mango", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Raisins", unit: "box" },
  { category: "Snacks & Breakfast", name: "Cereal (corn flakes)", unit: "box" },
  { category: "Snacks & Breakfast", name: "Cereal (granola)", unit: "box" },
  { category: "Snacks & Breakfast", name: "Cereal (oat clusters)", unit: "box" },
  { category: "Snacks & Breakfast", name: "Instant Oatmeal Packets", unit: "box" },
  { category: "Snacks & Breakfast", name: "Pancake Mix", unit: "box" },
  { category: "Snacks & Breakfast", name: "Waffle Mix", unit: "box" },
  { category: "Snacks & Breakfast", name: "Syrup (pancake)", unit: "bottle" },
  { category: "Snacks & Breakfast", name: "Pop-Tarts", unit: "box" },
  { category: "Snacks & Breakfast", name: "Frozen Waffles", unit: "box" },
  { category: "Snacks & Breakfast", name: "Bagels", unit: "pack" },
  { category: "Snacks & Breakfast", name: "English Muffins", unit: "pack" },
  { category: "Snacks & Breakfast", name: "Cream Cheese", unit: "pack" },
  { category: "Snacks & Breakfast", name: "Dark Chocolate Bars", unit: "bar" },
  { category: "Snacks & Breakfast", name: "Chocolate Chips", unit: "bag" },
  { category: "Snacks & Breakfast", name: "Graham Crackers", unit: "box" },
  { category: "Snacks & Breakfast", name: "Marshmallows", unit: "bag" },

  // ─── Beverages ─────────────────────────────────────────────────────────────
  { category: "Beverages", name: "Coffee (ground)", unit: "bag" },
  { category: "Beverages", name: "Coffee (whole bean)", unit: "bag" },
  { category: "Beverages", name: "K-Cup Pods", unit: "box" },
  { category: "Beverages", name: "Decaf Coffee", unit: "bag" },
  { category: "Beverages", name: "Espresso Pods", unit: "box" },
  { category: "Beverages", name: "Black Tea (bags)", unit: "box" },
  { category: "Beverages", name: "Green Tea (bags)", unit: "box" },
  { category: "Beverages", name: "Herbal Tea Assortment", unit: "box" },
  { category: "Beverages", name: "Sparkling Water (cans)", unit: "12-pack" },
  { category: "Beverages", name: "Sparkling Water (bottles)", unit: "pack" },
  { category: "Beverages", name: "Still Water (bottles)", unit: "case" },
  { category: "Beverages", name: "Orange Juice", unit: "carton" },
  { category: "Beverages", name: "Apple Juice", unit: "bottle" },
  { category: "Beverages", name: "Cranberry Juice", unit: "bottle" },
  { category: "Beverages", name: "Sports Drinks (Gatorade)", unit: "bottle" },
  { category: "Beverages", name: "Energy Drinks", unit: "can" },
  { category: "Beverages", name: "Soda (Coke)", unit: "12-pack" },
  { category: "Beverages", name: "Soda (Diet Coke)", unit: "12-pack" },
  { category: "Beverages", name: "Soda (Sprite)", unit: "12-pack" },
  { category: "Beverages", name: "Seltzer / Club Soda", unit: "bottle" },
  { category: "Beverages", name: "Tonic Water", unit: "bottle" },
  { category: "Beverages", name: "Almond Milk", unit: "carton" },
  { category: "Beverages", name: "Oat Milk", unit: "carton" },
  { category: "Beverages", name: "Protein Powder (vanilla)", unit: "container" },
  { category: "Beverages", name: "Protein Powder (chocolate)", unit: "container" },
  { category: "Beverages", name: "Hot Cocoa Mix", unit: "box" },
  { category: "Beverages", name: "Creamer (liquid)", unit: "bottle" },
  { category: "Beverages", name: "Creamer (powder)", unit: "container" },

  // ─── Bathroom & Personal Care ──────────────────────────────────────────────
  { category: "Bathroom & Personal Care", name: "Body Wash / Shower Gel", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Bar Soap", unit: "bar" },
  { category: "Bathroom & Personal Care", name: "Hand Soap (liquid)", unit: "pump" },
  { category: "Bathroom & Personal Care", name: "Hand Soap Refill", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Shampoo", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Conditioner", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Dry Shampoo", unit: "can" },
  { category: "Bathroom & Personal Care", name: "Toothpaste", unit: "tube" },
  { category: "Bathroom & Personal Care", name: "Toothbrush", unit: "each" },
  { category: "Bathroom & Personal Care", name: "Electric Toothbrush Heads", unit: "pack" },
  { category: "Bathroom & Personal Care", name: "Mouthwash", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Dental Floss", unit: "pack" },
  { category: "Bathroom & Personal Care", name: "Floss Picks", unit: "bag" },
  { category: "Bathroom & Personal Care", name: "Deodorant / Antiperspirant", unit: "stick" },
  { category: "Bathroom & Personal Care", name: "Moisturizing Lotion", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Face Wash / Cleanser", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Sunscreen (SPF 50)", unit: "bottle" },
  { category: "Bathroom & Personal Care", name: "Lip Balm (ChapStick)", unit: "each" },
  { category: "Bathroom & Personal Care", name: "Shaving Cream / Gel", unit: "can" },
  { category: "Bathroom & Personal Care", name: "Razors / Razor Blades", unit: "pack" },
  { category: "Bathroom & Personal Care", name: "Cotton Balls", unit: "bag" },
  { category: "Bathroom & Personal Care", name: "Cotton Swabs (Q-tips)", unit: "box" },
  { category: "Bathroom & Personal Care", name: "Feminine Hygiene Products", unit: "box" },
  { category: "Bathroom & Personal Care", name: "Hair Ties / Hair Bands", unit: "pack" },
  { category: "Bathroom & Personal Care", name: "Nail Clippers", unit: "each" },
  { category: "Bathroom & Personal Care", name: "Tweezers", unit: "each" },
  { category: "Bathroom & Personal Care", name: "Loofa / Bath Sponge", unit: "each" },
  { category: "Bathroom & Personal Care", name: "Shower Cap", unit: "each" },
  { category: "Bathroom & Personal Care", name: "Pumice Stone", unit: "each" },
  { category: "Bathroom & Personal Care", name: "Disposable Razors", unit: "pack" },

  // ─── First Aid & Medicine ──────────────────────────────────────────────────
  { category: "First Aid & Medicine", name: "Bandages / Band-Aids (assorted)", unit: "box" },
  { category: "First Aid & Medicine", name: "Gauze Pads", unit: "pack" },
  { category: "First Aid & Medicine", name: "Medical Tape", unit: "roll" },
  { category: "First Aid & Medicine", name: "Antiseptic / Hydrogen Peroxide", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Antibiotic Ointment (Neosporin)", unit: "tube" },
  { category: "First Aid & Medicine", name: "Hydrocortisone Cream", unit: "tube" },
  { category: "First Aid & Medicine", name: "Ace Bandage / Elastic Wrap", unit: "each" },
  { category: "First Aid & Medicine", name: "Ibuprofen (Advil)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Acetaminophen (Tylenol)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Aspirin", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Antacid (Tums)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Pepto-Bismol", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Allergy Medicine (Benadryl)", unit: "box" },
  { category: "First Aid & Medicine", name: "Allergy Medicine (Claritin)", unit: "box" },
  { category: "First Aid & Medicine", name: "Cold & Flu Medicine (Dayquil)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Cold & Flu Medicine (Nyquil)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Cough Drops", unit: "bag" },
  { category: "First Aid & Medicine", name: "Nasal Spray (Flonase)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Eye Drops (lubricating)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Thermometer", unit: "each" },
  { category: "First Aid & Medicine", name: "Heating Pad", unit: "each" },
  { category: "First Aid & Medicine", name: "Ice Pack / Cold Pack", unit: "each" },
  { category: "First Aid & Medicine", name: "Vitamin C (1000mg)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Vitamin D3", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Multivitamin", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Melatonin (sleep aid)", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Probiotics", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Magnesium", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Fish Oil / Omega-3", unit: "bottle" },
  { category: "First Aid & Medicine", name: "Zinc Supplements", unit: "bottle" },

  // ─── Laundry & Linen ──────────────────────────────────────────────────────
  { category: "Laundry & Linen", name: "Stain Remover Pen (Tide To Go)", unit: "each" },
  { category: "Laundry & Linen", name: "Mesh Laundry Bag (delicates)", unit: "each" },
  { category: "Laundry & Linen", name: "Wool Dryer Balls", unit: "pack" },
  { category: "Laundry & Linen", name: "Washing Machine Cleaner Tablets", unit: "pack" },
  { category: "Laundry & Linen", name: "Ironing Board Cover", unit: "each" },
  { category: "Laundry & Linen", name: "Starch Spray", unit: "can" },

  // ─── Pet Supplies ──────────────────────────────────────────────────────────
  { category: "Pet Supplies", name: "Dry Dog Food", unit: "bag" },
  { category: "Pet Supplies", name: "Wet Dog Food (canned)", unit: "can" },
  { category: "Pet Supplies", name: "Dog Treats", unit: "bag" },
  { category: "Pet Supplies", name: "Dry Cat Food", unit: "bag" },
  { category: "Pet Supplies", name: "Wet Cat Food (canned)", unit: "can" },
  { category: "Pet Supplies", name: "Cat Treats", unit: "bag" },
  { category: "Pet Supplies", name: "Cat Litter", unit: "bag" },
  { category: "Pet Supplies", name: "Cat Litter Box Liners", unit: "box" },
  { category: "Pet Supplies", name: "Pet Waste Bags (poop bags)", unit: "roll" },
  { category: "Pet Supplies", name: "Pet Shampoo", unit: "bottle" },
  { category: "Pet Supplies", name: "Flea & Tick Prevention", unit: "pack" },
  { category: "Pet Supplies", name: "Pet Enzymatic Cleaner (accidents)", unit: "bottle" },
  { category: "Pet Supplies", name: "Pet Brush / Grooming Brush", unit: "each" },
  { category: "Pet Supplies", name: "Dog Pee Pads", unit: "pack" },
  { category: "Pet Supplies", name: "Aquarium / Fish Food", unit: "container" },

  // ─── Outdoor & Garden ──────────────────────────────────────────────────────
  { category: "Outdoor & Garden", name: "Sunscreen Spray (outdoor use)", unit: "can" },
  { category: "Outdoor & Garden", name: "Insect Repellent (DEET)", unit: "can" },
  { category: "Outdoor & Garden", name: "Bug Spray (OFF!)", unit: "can" },
  { category: "Outdoor & Garden", name: "Wasp / Hornet Spray", unit: "can" },
  { category: "Outdoor & Garden", name: "Ant Traps / Bait Stations", unit: "pack" },
  { category: "Outdoor & Garden", name: "Roach Bait Stations", unit: "pack" },
  { category: "Outdoor & Garden", name: "Fertilizer (lawn)", unit: "bag" },
  { category: "Outdoor & Garden", name: "Weed Killer (Roundup)", unit: "bottle" },
  { category: "Outdoor & Garden", name: "Potting Mix / Soil", unit: "bag" },
  { category: "Outdoor & Garden", name: "Mulch", unit: "bag" },
  { category: "Outdoor & Garden", name: "Garden Hose Nozzle", unit: "each" },
  { category: "Outdoor & Garden", name: "Grass Seed", unit: "bag" },
  { category: "Outdoor & Garden", name: "Ice Melt / De-Icer", unit: "bag" },
  { category: "Outdoor & Garden", name: "Charcoal (BBQ)", unit: "bag" },
  { category: "Outdoor & Garden", name: "Lighter Fluid", unit: "bottle" },
  { category: "Outdoor & Garden", name: "Propane Tank (small)", unit: "each" },
  { category: "Outdoor & Garden", name: "Citronella Candles", unit: "each" },
  { category: "Outdoor & Garden", name: "Outdoor Furniture Cleaner", unit: "bottle" },
  { category: "Outdoor & Garden", name: "Deck / Wood Stain", unit: "can" },
  { category: "Outdoor & Garden", name: "Paint (outdoor / trim)", unit: "gallon" },

  // ─── Tools & Hardware ──────────────────────────────────────────────────────
  { category: "Tools & Hardware", name: "AA Batteries", unit: "pack" },
  { category: "Tools & Hardware", name: "AAA Batteries", unit: "pack" },
  { category: "Tools & Hardware", name: "9V Batteries", unit: "pack" },
  { category: "Tools & Hardware", name: "D Batteries", unit: "pack" },
  { category: "Tools & Hardware", name: "CR2032 Coin Batteries", unit: "pack" },
  { category: "Tools & Hardware", name: "Lightbulbs (LED A19 60W equiv)", unit: "pack" },
  { category: "Tools & Hardware", name: "Lightbulbs (LED small base)", unit: "pack" },
  { category: "Tools & Hardware", name: "Lightbulbs (smart / Hue)", unit: "each" },
  { category: "Tools & Hardware", name: "Fluorescent Tube Bulbs", unit: "pack" },
  { category: "Tools & Hardware", name: "Extension Cord", unit: "each" },
  { category: "Tools & Hardware", name: "Power Strip", unit: "each" },
  { category: "Tools & Hardware", name: "Surge Protector", unit: "each" },
  { category: "Tools & Hardware", name: "Duct Tape", unit: "roll" },
  { category: "Tools & Hardware", name: "Painter's Tape", unit: "roll" },
  { category: "Tools & Hardware", name: "Masking Tape", unit: "roll" },
  { category: "Tools & Hardware", name: "Clear Packing Tape", unit: "roll" },
  { category: "Tools & Hardware", name: "Super Glue", unit: "tube" },
  { category: "Tools & Hardware", name: "Gorilla Glue", unit: "bottle" },
  { category: "Tools & Hardware", name: "Wood Glue", unit: "bottle" },
  { category: "Tools & Hardware", name: "Picture Hanging Strips (Command Strips)", unit: "pack" },
  { category: "Tools & Hardware", name: "Velcro Strips (adhesive)", unit: "pack" },
  { category: "Tools & Hardware", name: "Assorted Screws & Nails", unit: "box" },
  { category: "Tools & Hardware", name: "Drywall Anchors", unit: "pack" },
  { category: "Tools & Hardware", name: "Wall Putty / Spackle", unit: "container" },
  { category: "Tools & Hardware", name: "Caulk (white silicone)", unit: "tube" },
  { category: "Tools & Hardware", name: "Caulk (paintable)", unit: "tube" },
  { category: "Tools & Hardware", name: "WD-40 Lubricant", unit: "can" },
  { category: "Tools & Hardware", name: "3-in-One Oil", unit: "can" },
  { category: "Tools & Hardware", name: "Sandpaper Assortment", unit: "pack" },
  { category: "Tools & Hardware", name: "Interior Paint (base white)", unit: "gallon" },
  { category: "Tools & Hardware", name: "Paint Rollers", unit: "pack" },
  { category: "Tools & Hardware", name: "Paint Brushes", unit: "pack" },
  { category: "Tools & Hardware", name: "Painter's Drop Cloth", unit: "each" },
  { category: "Tools & Hardware", name: "Smoke Detector Battery", unit: "pack" },
  { category: "Tools & Hardware", name: "Zip Ties (cable ties)", unit: "bag" },
  { category: "Tools & Hardware", name: "Rubber Bands (assorted)", unit: "bag" },
  { category: "Tools & Hardware", name: "Twist Ties", unit: "bag" },
  { category: "Tools & Hardware", name: "S-Hooks", unit: "pack" },
  { category: "Tools & Hardware", name: "Bungee Cords", unit: "pack" },
  { category: "Tools & Hardware", name: "Furnace Filters (20x25x1)", unit: "each" },
  { category: "Tools & Hardware", name: "Furnace Filters (16x25x1)", unit: "each" },
  { category: "Tools & Hardware", name: "Water Filter (refrigerator)", unit: "each" },
  { category: "Tools & Hardware", name: "Water Filter Pitcher Cartridge", unit: "each" },
  { category: "Tools & Hardware", name: "Drain Strainer (kitchen sink)", unit: "each" },
  { category: "Tools & Hardware", name: "Shower Drain Cover", unit: "each" },

  // ─── Office & School ───────────────────────────────────────────────────────
  { category: "Office & School", name: "Printer Paper (8.5x11)", unit: "ream" },
  { category: "Office & School", name: "Printer Ink Cartridges", unit: "set" },
  { category: "Office & School", name: "Ballpoint Pens", unit: "pack" },
  { category: "Office & School", name: "Pencils", unit: "pack" },
  { category: "Office & School", name: "Highlighters", unit: "pack" },
  { category: "Office & School", name: "Markers (Sharpie)", unit: "pack" },
  { category: "Office & School", name: "Dry-Erase Markers", unit: "pack" },
  { category: "Office & School", name: "Sticky Notes (Post-its)", unit: "pack" },
  { category: "Office & School", name: "Notepad / Legal Pad", unit: "each" },
  { category: "Office & School", name: "Stapler + Staples", unit: "each" },
  { category: "Office & School", name: "Tape Dispenser + Tape", unit: "each" },
  { category: "Office & School", name: "Scissors", unit: "each" },
  { category: "Office & School", name: "Ruler", unit: "each" },
  { category: "Office & School", name: "Paper Clips", unit: "box" },
  { category: "Office & School", name: "Binder Clips (assorted)", unit: "box" },
  { category: "Office & School", name: "Rubber Bands", unit: "bag" },
  { category: "Office & School", name: "File Folders", unit: "pack" },
  { category: "Office & School", name: "Mailing Envelopes (Letter)", unit: "box" },
  { category: "Office & School", name: "Bubble Mailers", unit: "pack" },
  { category: "Office & School", name: "Shipping Labels", unit: "pack" },
  { category: "Office & School", name: "Postage Stamps", unit: "book" },
  { category: "Office & School", name: "Calculator", unit: "each" },
  { category: "Office & School", name: "Flash Drives (USB)", unit: "each" },
  { category: "Office & School", name: "HDMI Cable", unit: "each" },
  { category: "Office & School", name: "Phone Charging Cables (Lightning)", unit: "each" },
  { category: "Office & School", name: "Phone Charging Cables (USB-C)", unit: "each" },
  { category: "Office & School", name: "USB Wall Charger", unit: "each" },
  { category: "Office & School", name: "Power Bank (portable)", unit: "each" },

  // ─── Safety & Emergency ────────────────────────────────────────────────────
  { category: "Safety & Emergency", name: "Smoke Detector", unit: "each" },
  { category: "Safety & Emergency", name: "Carbon Monoxide Detector", unit: "each" },
  { category: "Safety & Emergency", name: "Fire Extinguisher (kitchen ABC)", unit: "each" },
  { category: "Safety & Emergency", name: "Flashlight", unit: "each" },
  { category: "Safety & Emergency", name: "Flashlight Batteries", unit: "pack" },
  { category: "Safety & Emergency", name: "Emergency Candles", unit: "pack" },
  { category: "Safety & Emergency", name: "Matches (long grill matches)", unit: "box" },
  { category: "Safety & Emergency", name: "Lighter (BIC)", unit: "each" },
  { category: "Safety & Emergency", name: "Emergency Water (gallon jug)", unit: "each" },
  { category: "Safety & Emergency", name: "Emergency Food Kit (3-day)", unit: "each" },
  { category: "Safety & Emergency", name: "N95 Masks", unit: "box" },
  { category: "Safety & Emergency", name: "Disposable Gloves (nitrile)", unit: "box" },
  { category: "Safety & Emergency", name: "Safety Goggles", unit: "each" },
  { category: "Safety & Emergency", name: "Work Gloves", unit: "pair" },
  { category: "Safety & Emergency", name: "Step Stool / 2-Step Ladder", unit: "each" },
  { category: "Safety & Emergency", name: "First Aid Kit (complete)", unit: "each" },
  { category: "Safety & Emergency", name: "Glow Sticks", unit: "pack" },
  { category: "Safety & Emergency", name: "Utility Knife / Box Cutter", unit: "each" },
  { category: "Safety & Emergency", name: "Packing Tape (heavy duty)", unit: "roll" },

  // ─── Baby & Children ───────────────────────────────────────────────────────
  { category: "Baby & Children", name: "Diapers (size 1)", unit: "pack" },
  { category: "Baby & Children", name: "Diapers (size 2)", unit: "pack" },
  { category: "Baby & Children", name: "Diapers (size 3)", unit: "pack" },
  { category: "Baby & Children", name: "Pull-Ups Training Pants", unit: "pack" },
  { category: "Baby & Children", name: "Baby Wipes", unit: "pack" },
  { category: "Baby & Children", name: "Diaper Rash Cream (Desitin)", unit: "tube" },
  { category: "Baby & Children", name: "Baby Shampoo (Johnson's)", unit: "bottle" },
  { category: "Baby & Children", name: "Baby Lotion", unit: "bottle" },
  { category: "Baby & Children", name: "Baby Powder", unit: "container" },
  { category: "Baby & Children", name: "Baby Formula", unit: "can" },
  { category: "Baby & Children", name: "Baby Food (stage 1 jars)", unit: "jar" },
  { category: "Baby & Children", name: "Baby Food Pouches", unit: "pack" },
  { category: "Baby & Children", name: "Toddler Sippy Cups", unit: "each" },
  { category: "Baby & Children", name: "Pacifiers", unit: "pack" },
  { category: "Baby & Children", name: "Bottle Brush Cleaner", unit: "each" },
  { category: "Baby & Children", name: "Teething Rings", unit: "each" },
  { category: "Baby & Children", name: "Children's Ibuprofen (Motrin)", unit: "bottle" },
  { category: "Baby & Children", name: "Children's Acetaminophen (Tylenol)", unit: "bottle" },
  { category: "Baby & Children", name: "Saline Nasal Drops (infant)", unit: "bottle" },
  { category: "Baby & Children", name: "Gripe Water", unit: "bottle" },

  // ─── Food Storage & Organization ──────────────────────────────────────────
  { category: "Food Storage & Organization", name: "Glass Storage Containers (set)", unit: "set" },
  { category: "Food Storage & Organization", name: "Plastic Storage Containers (set)", unit: "set" },
  { category: "Food Storage & Organization", name: "Mason Jars (16 oz)", unit: "pack" },
  { category: "Food Storage & Organization", name: "Mason Jars (32 oz)", unit: "pack" },
  { category: "Food Storage & Organization", name: "Produce Bags (reusable)", unit: "set" },
  { category: "Food Storage & Organization", name: "Silicone Food Bags (reusable)", unit: "set" },
  { category: "Food Storage & Organization", name: "Beeswax Wraps", unit: "set" },
  { category: "Food Storage & Organization", name: "Vacuum Seal Bags", unit: "box" },
  { category: "Food Storage & Organization", name: "Pantry Labels / Label Maker Tape", unit: "roll" },
  { category: "Food Storage & Organization", name: "Lazy Susan (pantry)", unit: "each" },
  { category: "Food Storage & Organization", name: "Shelf Risers", unit: "set" },
  { category: "Food Storage & Organization", name: "Bin / Basket (organizing)", unit: "each" },

  // ─── Home Decor & Comfort ──────────────────────────────────────────────────
  { category: "Home Decor & Comfort", name: "Candles (pillar / scented)", unit: "each" },
  { category: "Home Decor & Comfort", name: "Wax Melts", unit: "pack" },
  { category: "Home Decor & Comfort", name: "Reed Diffuser Refill", unit: "bottle" },
  { category: "Home Decor & Comfort", name: "Throw Blanket", unit: "each" },
  { category: "Home Decor & Comfort", name: "Throw Pillows", unit: "each" },
  { category: "Home Decor & Comfort", name: "Picture Frames (5x7)", unit: "each" },
  { category: "Home Decor & Comfort", name: "Picture Frames (8x10)", unit: "each" },
  { category: "Home Decor & Comfort", name: "Vase (decorative)", unit: "each" },
  { category: "Home Decor & Comfort", name: "Battery-Powered Fairy Lights", unit: "set" },

  // ─── Seasonal & Holidays ───────────────────────────────────────────────────
  { category: "Seasonal & Holidays", name: "Holiday Gift Wrap", unit: "roll" },
  { category: "Seasonal & Holidays", name: "Gift Bags (assorted sizes)", unit: "pack" },
  { category: "Seasonal & Holidays", name: "Tissue Paper (gift bags)", unit: "pack" },
  { category: "Seasonal & Holidays", name: "Gift Bows & Ribbons", unit: "pack" },
  { category: "Seasonal & Holidays", name: "Greeting Cards (assorted)", unit: "pack" },
  { category: "Seasonal & Holidays", name: "Halloween Candy (assorted)", unit: "bag" },
  { category: "Seasonal & Holidays", name: "Valentine's Day Chocolates", unit: "box" },
  { category: "Seasonal & Holidays", name: "Christmas Tree Lights (LED)", unit: "set" },
  { category: "Seasonal & Holidays", name: "Holiday Decorations (assorted)", unit: "box" },
  { category: "Seasonal & Holidays", name: "Birthday Candles", unit: "pack" },
  { category: "Seasonal & Holidays", name: "Balloons (latex)", unit: "bag" },
  { category: "Seasonal & Holidays", name: "Streamers / Party Decorations", unit: "pack" },
  { category: "Seasonal & Holidays", name: "Party Plates & Napkins (themed)", unit: "set" },
];

async function main() {
  // Find demo household
  const household = await prisma.household.findFirst({
    orderBy: { createdAt: "asc" },
  });

  if (!household) {
    console.error("No household found. Run npm run db:seed first.");
    process.exit(1);
  }

  console.log(`Seeding ${ITEMS.length} inventory items for: ${household.name}`);

  let created = 0;
  let skipped = 0;

  for (const item of ITEMS) {
    const existing = await prisma.inventoryItem.findFirst({
      where: { householdId: household.id, name: item.name },
    });

    if (existing) {
      // Update category/unit if missing
      if (!existing.category || !existing.unit) {
        await prisma.inventoryItem.update({
          where: { id: existing.id },
          data: {
            category: existing.category ?? item.category,
            unit: existing.unit ?? item.unit,
          },
        });
      }
      skipped++;
    } else {
      await prisma.inventoryItem.create({
        data: {
          householdId: household.id,
          name: item.name,
          category: item.category,
          unit: item.unit,
          qty: 0,
          threshold: 1,
          productUrl: null,
        },
      });
      created++;
    }
  }

  console.log(`✅ Done: ${created} created, ${skipped} already existed.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
